// <auto-generated />
namespace Books.Web.DataContexts.BookMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameBookProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameBookProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201706180946004_RenameBookProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
